### PR TITLE
test

### PR DESCRIPTION
**Pull request by kisphp**

### CODE REVIEW

**Comment by kisphp** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Failed**: This project is currently locked by an unapplied plan from pull #12. To continue, delete the lock from #12 or apply that plan and merge the pull request.

Once the lock is released, comment `atlantis plan` here to re-plan.

**Comment by kisphp** [comment]
atlantis plan

**Comment by kisphp** [comment]
Ran Plan for 2 projects:

1. project: `app-1` dir: `app-1` workspace: `default`
1. project: `app-2` dir: `app-2` workspace: `default`

### 1. project: `app-1` dir: `app-1` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-19T21:24:43Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/13/default/app-1/app-1-default.json"
time="2022-05-19T21:24:43Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-19T21:24:43Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-19T21:24:44Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-13/app-1-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             32.67µs
  parsing              186.621µs
  adaptation           56.254µs
  checks               109.909996ms
  total                110.185541ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     6
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-1`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab1717.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-1%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-1`
</details>


---
### 2. project: `app-2` dir: `app-2` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-19T21:25:11Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/13/default/app-2/app-2-default.json"
time="2022-05-19T21:25:11Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-19T21:25:11Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-19T21:25:11Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-13/app-2-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             40.763µs
  parsing              3.588035ms
  adaptation           133.557µs
  checks               185.587489ms
  total                189.349844ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     6
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab1717.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-2`
</details>


---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by kisphp** [comment]
Ran Plan for 2 projects:

1. project: `app-1` dir: `app-1` workspace: `default`
1. project: `app-2` dir: `app-2` workspace: `default`

### 1. project: `app-1` dir: `app-1` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-19T21:28:02Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/13/default/app-1/app-1-default.json"
time="2022-05-19T21:28:02Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-19T21:28:02Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-19T21:28:03Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-13/app-1-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             39.021µs
  parsing              433.07µs
  adaptation           73.875µs
  checks               111.23662ms
  total                111.782586ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     6
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-1`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab1717.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-1%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-1`
</details>


---
### 2. project: `app-2` dir: `app-2` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-19T21:28:31Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/13/default/app-2/app-2-default.json"
time="2022-05-19T21:28:31Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-19T21:28:31Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-19T21:28:31Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-13/app-2-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             38.14µs
  parsing              212.079µs
  adaptation           54.364µs
  checks               194.282162ms
  total                194.586745ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     6
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab1717.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-2`
</details>


---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by kisphp** [comment]
atlantis unlock

**Comment by kisphp** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Comment by kisphp** [comment]
atlantis plan

**Comment by kisphp** [comment]
Ran Plan for 2 projects:

1. project: `app-1` dir: `app-1` workspace: `default`
1. project: `app-2` dir: `app-2` workspace: `default`

### 1. project: `app-1` dir: `app-1` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-19T21:30:01Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/13/default/app-1/app-1-default.json"
time="2022-05-19T21:30:01Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-19T21:30:01Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-19T21:30:01Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-13/app-1-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             26.621µs
  parsing              159.683µs
  adaptation           49.388µs
  checks               110.620438ms
  total                110.85613ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     6
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-1`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab1717.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-1%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-1`
</details>


---
### 2. project: `app-2` dir: `app-2` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-19T21:30:30Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/13/default/app-2/app-2-default.json"
time="2022-05-19T21:30:30Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-19T21:30:30Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-19T21:30:30Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-13/app-2-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             26.175µs
  parsing              174.59µs
  adaptation           50.642µs
  checks               189.213057ms
  total                189.464464ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     6
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab1717.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-2`
</details>


---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by bogdan-rizac — APPROVED** [review]

**Review by kp-gh-1 — APPROVED** [review]

**Comment by kisphp** [comment]
atlantis apply

**Comment by kisphp** [comment]
Ran Apply for 2 projects:

1. project: `app-1` dir: `app-1` workspace: `default`
1. project: `app-2` dir: `app-2` workspace: `default`

### 1. project: `app-1` dir: `app-1` workspace: `default`
```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data-1 = "my data 1"
data-2 = "my data 2"
data-2-1 = "my data 2-1"
name = "github-atlantis-hook"

```

---
### 2. project: `app-2` dir: `app-2` workspace: `default`
```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data-1 = "my data 1"
data-2 = "my data 2"
data-2-1 = "my data 2-1"
name = "github-atlantis-hook"

```

---

**Comment by kisphp** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by kisphp** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `app-1` workspace: `default`
- dir: `app-2` workspace: `default`

**Pull request merged**
