### PR TITLE
test change

### PR DESCRIPTION
**Pull request by kisphp**

### CODE REVIEW

**Comment by kisphp** [comment]
Ran Plan for project: `app-2` dir: `app-2` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-3 = "my data 3"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-19T21:38:38Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/14/default/app-2/app-2-default.json"
time="2022-05-19T21:38:38Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-19T21:38:38Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-19T21:38:38Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-14/app-2-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             25.681µs
  parsing              202.998µs
  adaptation           51.299µs
  checks               198.484692ms
  total                198.76467ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     7
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab1717.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-2`
</details>


---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by bogdan-rizac — APPROVED** [review]

**Review by kp-gh-1 — APPROVED** [review]

**Comment by kp-gh-1** [comment]
atlantis apply

**Comment by kisphp** [comment]
Ran Apply for project: `app-2` dir: `app-2` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data-1 = "my data 1"
data-2 = "my data 2"
data-2-1 = "my data 2-1"
data-3 = "my data 3"
name = "github-atlantis-hook"

```

**Comment by kisphp** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by kisphp** [comment]
atlantis plan

**Comment by kisphp** [comment]
Ran Plan for project: `app-2` dir: `app-2` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

time="2022-05-19T21:43:09Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/14/default/app-2/app-2-default.json"
time="2022-05-19T21:43:09Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-19T21:43:09Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-19T21:43:10Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-14/app-2-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             25.602µs
  parsing              281.751µs
  adaptation           53.774µs
  checks               111.57366ms
  total                111.934787ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     7
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab1717.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-2`
</details>
No changes. Your infrastructure matches the configuration.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by kisphp** [comment]
atlantis apply

**Comment by kisphp** [comment]
Ran Apply for project: `app-2` dir: `app-2` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data-1 = "my data 1"
data-2 = "my data 2"
data-2-1 = "my data 2-1"
data-3 = "my data 3"
name = "github-atlantis-hook"

```

**Comment by kisphp** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by kisphp** [comment]
atlantis plan

**Comment by kisphp** [comment]
Ran Plan for project: `app-2` dir: `app-2` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

time="2022-05-19T22:09:02Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/14/default/app-2/app-2-default.json"
time="2022-05-19T22:09:02Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-19T22:09:02Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-19T22:09:02Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-14/app-2-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             25.291µs
  parsing              192.786µs
  adaptation           49.335µs
  checks               193.896369ms
  total                194.163781ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     7
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab1717.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-2`
</details>
No changes. Your infrastructure matches the configuration.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by kisphp** [comment]
atlantis apply

**Comment by kisphp** [comment]
Ran Apply for project: `app-2` dir: `app-2` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data-1 = "my data 1"
data-2 = "my data 2"
data-2-1 = "my data 2-1"
data-3 = "my data 3"
name = "github-atlantis-hook"

```

**Comment by kisphp** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by kisphp** [comment]
atlantis apply

**Comment by kisphp** [comment]
Ran Apply for 0 projects:

**Comment by kisphp** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by kisphp** [comment]
Ran Plan for dir: `app-2` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
exit status 1: running "$TERRAFORM_BINARY init -input=false -no-color >/dev/null" in "/home/atlantis/.atlantis/repos/kisphp-apps/iac-github/14/default/app-2": 

Error: Failed to get existing workspaces: S3 bucket does not exist.

The referenced S3 bucket must have been previously created. If the S3 bucket
was created within the last minute, please wait for a minute or two and try
again.

Error: NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: CHXFVW0MEQYQZZKG, host id: UMC/mo+VjYkK8/iyA6ElGE/NyLRbw3yMTu5SsA1kzEnTJgsnbiPCGUGQa1FBP31jtG8WKhg8J2g=




Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html

```
</details>

**Comment by kisphp** [comment]
Ran Plan for 2 projects:

1. project: `app-1` dir: `app-1` workspace: `default`
1. project: `app-2` dir: `app-2` workspace: `default`

### 1. project: `app-1` dir: `app-1` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-20T09:47:15Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/14/default/app-1/app-1-default.json"
time="2022-05-20T09:47:15Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-20T09:47:15Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-20T09:47:16Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-14/app-1-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             26.327µs
  parsing              170.507µs
  adaptation           52.585µs
  checks               201.064044ms
  total                201.313463ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     6
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-1`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab351.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-1%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-1`
</details>


---
### 2. project: `app-2` dir: `app-2` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + data-3   = "my data 3"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-20T09:47:43Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/14/default/app-2/app-2-default.json"
time="2022-05-20T09:47:43Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-20T09:47:43Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-20T09:47:44Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-14/app-2-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             28.638µs
  parsing              190.685µs
  adaptation           106.369µs
  checks               194.37017ms
  total                194.695862ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     7
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab351.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-2`
</details>


---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by kisphp** [comment]
atlantis plan

**Comment by kisphp** [comment]
Ran Plan for 2 projects:

1. project: `app-1` dir: `app-1` workspace: `default`
1. project: `app-2` dir: `app-2` workspace: `default`

### 1. project: `app-1` dir: `app-1` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-20T11:57:49Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/14/default/app-1/app-1-default.json"
time="2022-05-20T11:57:49Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-20T11:57:49Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-20T11:57:50Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-14/app-1-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             24.643µs
  parsing              169.334µs
  adaptation           63.91µs
  checks               193.170343ms
  total                193.42823ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     6
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-1`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab430.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-1%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-1`
</details>


---
### 2. project: `app-2` dir: `app-2` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + data-3   = "my data 3"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-20T11:58:16Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/14/default/app-2/app-2-default.json"
time="2022-05-20T11:58:16Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-20T11:58:16Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-20T11:58:17Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-14/app-2-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             23.944µs
  parsing              206.307µs
  adaptation           53.205µs
  checks               107.513476ms
  total                107.796932ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     7
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab430.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-2`
</details>


---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by kisphp** [comment]
atlantis apply

**Comment by kisphp** [comment]
Ran Apply for 2 projects:

1. project: `app-1` dir: `app-1` workspace: `default`
1. project: `app-2` dir: `app-2` workspace: `default`

### 1. project: `app-1` dir: `app-1` workspace: `default`
```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data-1 = "my data 1"
data-2 = "my data 2"
data-2-1 = "my data 2-1"
name = "github-atlantis-hook"

```

---
### 2. project: `app-2` dir: `app-2` workspace: `default`
```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data-1 = "my data 1"
data-2 = "my data 2"
data-2-1 = "my data 2-1"
data-3 = "my data 3"
name = "github-atlantis-hook"

```

---

**Comment by kisphp** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by kisphp** [comment]
atlantis apply

**Comment by kisphp** [comment]
Ran Apply for 0 projects:

**Comment by kisphp** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by kisphp** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `app-1` workspace: `default`
- dir: `app-2` workspace: `default`

**Pull request merged**
