### PR TITLE
new output

### PR DESCRIPTION
**Pull request by kisphp**

### CODE REVIEW

**Comment by kisphp** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1 = "my data 1"
  + data-2 = "my data 2"
  + data-3 = "my data 3"
  + name   = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-19T21:15:43Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/12/default/default.json"
time="2022-05-19T21:15:43Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-19T21:15:43Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-19T21:15:43Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-12/-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             23.427µs
  parsing              175.11µs
  adaptation           55.032µs
  checks               190.909103ms
  total                191.162672ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     6
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab1717.info/lock?id=kisphp-apps%252Fiac-github%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>


---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by kisphp** [comment]
atlantis apply

**Comment by kisphp** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Failed**: Pull request must be mergeable before running apply.

**Review by bogdan-rizac — APPROVED** [review]

**Comment by kisphp** [comment]
atlantis apply

**Comment by kisphp** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Failed**: Pull request must be mergeable before running apply.

**Comment by kisphp** [comment]
atlantis unlock

**Comment by kisphp** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Pull request closed without merging**
