### PR TITLE
test merging 5

### PR DESCRIPTION
**Pull request by kisphp**

### CODE REVIEW

**Review by bogdan-rizac — APPROVED** [review]

**Comment by kisphp** [comment]
Ran Plan for project: `app-1` dir: `app-1` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0

Your version of Terraform is out of date! The latest version
is 1.2.0. You can update by downloading from https://www.terraform.io/downloads.html


Changes to Outputs:
  + data-1   = "my data 1"
  + data-2   = "my data 2"
  + data-2-1 = "my data 2-1"
  + data-3   = "my data 3"
  + name     = "github-atlantis-hook"

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

time="2022-05-20T12:23:30Z" level=info msg="Detected Terraform plan JSON file at /home/atlantis/.atlantis/repos/kisphp-apps/iac-github/16/default/app-1/app-1-default.json"
time="2022-05-20T12:23:30Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-20T12:23:30Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-20T12:23:30Z" level=info msg="Output saved to /tmp/kisphp-apps-iac-github-16/app-1-infracost.json"

  timings
  ──────────────────────────────────────────
  disk i/o             42.948µs
  parsing              771.84µs
  adaptation           85.856µs
  checks               196.556909ms
  total                197.457553ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    1
  blocks processed     7
  files read           2

  results
  ──────────────────────────────────────────
  passed               0
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!


custom terraform plan

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p app-1`
* :put_litter_in_its_place: To **delete** this plan click [here](https://blue.cmcloudlab430.info/lock?id=kisphp-apps%252Fiac-github%252Fapp-1%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p app-1`
</details>


---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by kp-gh-1 — APPROVED** [review]

**Comment by kisphp** [comment]
atlantis apply

**Comment by kisphp** [comment]
Ran Apply for project: `app-1` dir: `app-1` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data-1 = "my data 1"
data-2 = "my data 2"
data-2-1 = "my data 2-1"
data-3 = "my data 3"
name = "github-atlantis-hook"

```

**Comment by kisphp** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by kisphp** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `app-1` workspace: `default`

**Pull request merged**
